### ISSUE TITLE
Missing NuGet dependency on Dyndle.Modules.Core

### ISSUE THREAD

**Issue by pjbeemster** [dyndle/dyndle-web#3]
Dyndle QuickStart web app install fails on missing NuGet dependency.

Steps to reproduce:
1. Follow steps 1-4 of the Dyndle Quickstart web app installation (https://www.dyndle.com/docs/quickstart-installation.html);
2. Step 5, installing `Dyndle.Modules.Core` fails with a NuGet unresolved dependency on `Trivident.RazorGenerator.Mvc`

```
Attempting to gather dependency information for package 'Dyndle.Modules.Core.1.0.0' with respect to project 'quickstart-web-dotnetfx', targeting '.NETFramework,Version=v4.8'
Gathering dependency information took 2.04 sec
Attempting to resolve dependencies for package 'Dyndle.Modules.Core.1.0.0' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'Trivident.RazorGenerator.Mvc'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.
Time Elapsed: 00:00:02.0547540
========== Finished ==========
```

Environment:

- Windows Server 2019 Standard;
- Visual Studio 2019 Community Edition;
- .NET Framework 4.8

**Comment by kunalshetye** [comment]
Fixed in [1.0.1](https://github.com/dyndle/dyndle-web/releases/tag/v1.0.1)
